spring:
  security:
    user:
#    - name: mainul35
#      password: "{noop}secret"
#      roles: ADMIN
      name: user
      password: "{noop}secret"
      roles: USER
    oauth2:
      authorization-server:
        client:
          client-1:
            registration:
              client-id: client-with-client-credentials
              client-secret: "{noop}secret1"
              authorization-grant-types: client_credentials
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret2"
              authorization-grant-types: "authorization_code"
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
              redirect-uris:
                - http://localhost:8081/login/oauth2/code/oidc-client
                - http://127.0.0.1:8080/oauth2/authorize
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logout"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"
            require-authorization-consent: true
        endpoint:
          token-uri: "/oauth2/token"
        issuer-uri: http://127.0.0.1:8080/issuer